### ISSUE TITLE
using latest W3C CG Template for Charter

### ISSUE THREAD

**Issue by wayneca** [webscreens/cg-charter#11]
This is long, but the short version is:

> The proposed Charter from @mfoltzgoogle isn't using the latest version of the [W3C Community Group Charter Template](https://github.com/w3c/cg-charter).  The proposed charter should copy the template from the "Community and Business Group Process" heading to the end. @anssiko 

The changes that have been made to the template since the one you used are important reordering of sections and moving paragraphs between decision process and transparency.  The changes aren't substantive but they're the order other groups liked better and I think it reads better.

New CGs often copy a popular CG rather than going to the W3C CG Charter template, so it would help to have this CG using the latest version.  (I don't see where I could do a PR for the proposal so haven't - but it's just a cut and paste of the whole process section).

I saw 4 substantive changes (that aren't just the reordering that was done).  I'll list those here in case those were intentional and you want to repeat them when you copy the process section.  If the changes are intentional, I'd like to hear about why they were wanted so we can consider changing the W3C template to match them. (that's how we've changed the template - based on what CGs using the template have wanted changed)
1. the proposed charter renames the entire process section as "Community and Business Group Process and Patent Policy".  The template calls that "Community and Business Group Process".  For what it's worth, the W3C patent policy is not on equal footing with the W3C Process.  The W3C Patent Policy has effect in W3C only because it is [normatively referenced by the W3C Process](https://www.w3.org/2005/10/Process-20051014/#pp).
2. In the second paragraph of the Process section, the proposed charter adds: "Proposals in this Community Group charter are applicable "Specification" in the CLA. "  That is a sentence that comes from the W3C Web Platform Incubator Group where they call specs "proposals".  It doesn't make sense in the context of this CG.  If someone makes a "proposal" that is not a Specification in this CG.  Specifications are the things this Charter says are specifications.
3. In "Contribution Mechanics", "For the same reason, the Community Group mailing list must not be used for making or discussing substantive contributions to Specifications." was removed in the proposed charter (or wasn't in the charter template at the time it was copied).  (looking at this I think that's poorly worded and am starting a different discussion to change that sentence - would help to know if it was removed on purpose in the proposed charter.)
4. In the "Transparency" section: "Meetings may be restricted to Community Group participants, but a public summary or minutes must be posted to the group's public mailing list, or to a GitHub issue if the group uses GitHub" was either removed in the proposed charter or not in because it wasn't in the earlier template that this used.  The idea there was to allow CG participant only meetings (because at places like W3C TPAC you can't have non-participants), but to ensure if the group meets where the public can't attend, the summary is still public. (anyone can agree to the CLA and join the CG)

**Comment by wayneca** [comment]
I made a pull request for these changes in the proposed charter.  In that I added notes at each place the proposed charter didn't include something in the new template.  the 4 things listed above plus the one that immediately follows here.

also there was a 5th difference.  the proposed charter didn't have the process paragraph that says the CG will only create the specs the charter says it can create.

**Comment by wayneca** [comment]
For the third difference above in Contribution Mechanics, we're removing the sentence in the charter template to match what yours.

**Comment by wayneca** [comment]
For 3 above, that sentence that you didn't have is now removed from the W3C CG Charter template.  We also removed the sentence before it.  You still have that sentence so the 3 bullet above would become remove the other sentence.  Here's what was removed from the template.

It doesn't matter if you leave that sentence for 3.  It was removed just because it isn't anything that matters at all.

> ```
>  Note: this Community Group will not use a contrib mailing list for contributions 
> since all contributions will be tracked via Github mechanisms 
>  (e.g. pull requests). For the same reason, the Community Group 
>  mailing list must not be used for making or discussing substantive contributions
> to Specifications.
> ```

**Comment by markafoltz** [comment]
@wcarr can this be closed now, or are there other changes you'd like to propose?

**Comment by wayneca** [comment]
It can be closed, thanks.
