### ISSUE TITLE
Define scope for localization and accessibility across user agents

### ISSUE THREAD

**Issue by markafoltz** [webscreens/cg-charter#12]
Copied from the charter draft:

> We should discuss whether extending localization and accessibility support across user agents is in scope for the Community Group.

This could involve sharing locale-specific resources across user agents, or extending screen reader support across user agents.

I can reach out to our accessibility experts internally, but perhaps @tidoust can liason with one of the WAI groups [1] to get an opinion about the state of this capability.

[1] https://www.w3.org/WAI/groups.html

**Comment by tidoust** [comment]
@mfoltzgoogle I'll get in touch with WAI folks but I would also like to understand better what you would like to achieve with this.

The main standards published by WAI groups for user agents are guidelines, not APIs:
- [User Agent Accessibility Guidelines (UAAG) 2.0](http://www.w3.org/TR/UAAG20/)
- [WAI-ARIA 1.0 User Agent Implementation Guide](http://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/)

In particular, my understanding is that assistive technologies rely on proprietary [Accessibility APIs](http://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/#def_accessibility_api) that depend on the platform these technologies run on.

Extending assistive technologies to work across user agents in a Presentation API context seems to require the definition of a proper ontology to describe all the information that needs to flow from the receiving UA to the controlling UA, possibly restricted to the elements of the [content user interface](http://www.w3.org/TR/2015/NOTE-UAAG20-Reference-20151215/#def-content-ui). That does not seem trivial.

Or did you have something else in mind?

**Comment by anssiko** [comment]
I'd suggest l11n and a11y are out of scope for the CG to keep scope reasonable.

WG deliverables undergo the [horizontal review](https://www.w3.org/Guide/Charter.html#horizontal-review) for related issues, but there are no formal requirements for CG work.

We can [amend the charter](https://webscreens.github.io/cg-charter/#charter-change) later, if the priority of this needs to be upped.

Please let us know if you think this topic should be in the charter from the start.

**Comment by markafoltz** [comment]
Sounds good, thanks @anssiko.
