### ISSUE TITLE
[meta] Decide on standards track for CG deliverables

### ISSUE THREAD

**Issue by markafoltz** [webscreens/cg-charter#13]
[This was extracted from a note in the charter.  Since the charter has explicit language about transferring its products to a standards track organization, I am removing the note and refiling this as an issue for future discussion.]

The process, structure, format and patent policies of prospective
standards bodies should be discussed before committing to a particular
standards track for this work.

**Comment by anssiko** [comment]
I think this note was relevant in the context of the Open Screen Protocol that had multiple possible standards track targets. Now that OSP migration to the Second Screen WG is underway, we've already discussed these aspects as a prerequisite for that.
