### ISSUE TITLE
Cherry-pick the latest developments from the CG Charter template

### ISSUE THREAD

**Issue by anssiko** [webscreens/cg-charter#9]
@wcarr has been revising and improving the CG Charter template:

https://wcarr.github.io/cg-charter/CGCharter.html

We should cherry-pick the latest developments to this proposed Second Screen CG Charter.

**Comment by markafoltz** [comment]
I believe this can be closed by the merger of the PR by @wcarr, followed by some additional updates.

**Comment by markafoltz** [comment]
@anssiko Can this issue be closed?  Thanks.
